irods/irods_capability_storage_tiering

- libirods_rule_engine_plugin-storage_tiering.cpp
- packaging/test_plugin_storage_tiering.py
Returning an error for non-pep_api_data_obj_get_post operations in exec_rule is not necessarily handling unsupported operations. The "unsupported" operations are applying access time metadata to data objects, but return an error because only pep_api_data_obj_get_post restages data to a different tier. The error has been removed because rule_exists should be catching unsupported rules.
Made tests more specific in order to catch failure to annotate metadata in the future.
> [#42] Remove SYS_NOT_SUPPORTED return in rule_exec

- irods_storage_tiering.cpp
- packaging/test_plugin_storage_tiering.py
Instead of tracking the object limit when iterating over results of
violating objects, the object limit can now be used as the query limit
in the vocabulary of the query iterator. The query iterator will cease
once the object limit has been reached. 256 will no longer indicate
"no object limit" - this is now represented by 0.
Also, change tests to fit new definition of 0 in query iterator.
---
[CI tests running](http://172.25.14.63:8080/job/rule-engine-plugin-storage-tiering-build-test-workflow/243/)
> [#45] Use query limit feature in query iterator (4-2-stable)

- irods_storage_tiering.cpp
- packaging/test_plugin_storage_tiering.py
Instead of tracking the object limit when iterating over results of
violating objects, the object limit can now be used as the query limit
in the vocabulary of the query iterator. The query iterator will cease
once the object limit has been reached. 256 will no longer indicate
"no object limit" - this is now represented by 0.
Also, change tests to fit new definition of 0 in query iterator.
---
[CI tests passed](http://172.25.14.63:8080/job/rule-engine-plugin-storage-tiering-build-test-workflow/246/)
> [#45] Use query limit feature in query iterator (master)

- irods_consortium_continuous_integration_test_hook.py
[CI tests running](http://172.25.14.63:8080/job/rule-engine-plugin-storage-tiering-build-test-workflow/283/)
> Fix test hook (4-2-stable)

- packaging/test_plugin_unified_storage_tiering.py
- storage_tiering.cpp
Due to some changes in how scheduling data migrations works, the unified
storage tiering REP needed to be updated in order to work. The following
changes were made:
- "policy" was changed to "policy_to_invoke" as expected in the cpp
default REP implementation of irods_policy_enqueue_rule
- "payload" was changed to "parameters" as expected in the cpp default
REP implementation of irods_policy_enqueue_rule
- "delay_conditions" was moved inside of the "parameters" JSON struct
as expected in the cpp default REP implementation of
irods_policy_enqueue_rule
This causes everything to align as expected in the new world of
policy-composed rule invocation.
CI tests running, but all tests passed at the bench. Fixed all of the log noise that I observed while running at the bench as well.
> [#165] Fix scheduled migration via default cpp REP (4-2-stable)

- unified_storage_tiering.cmake
Workaround for linker error caused by fmt not being passed down as a dependency in irods-dev (irods/irods#5669)
> [irods/irods#5828] Explicitly link to libfmt

- example_unified_tiering_invocation.r
- irods_consortium_continuous_integration_build_hook.py
- irods_consortium_continuous_integration_test_hook.py
- packaging/test_plugin_unified_storage_tiering.py
- storage_tiering.cpp
These tests do *NOT* pass presently. I suspect there is a bug in the delay server as the tests do pass in 4-2-stable. If you diff this against 4-2-stable, you will see that the only difference of any possible consequence is the fetching of configuration values, and I don't think that is related to the issues I am seeing. I could be wrong, of course. :) Leaving as draft until we can figure it out.
> Build/test hook improvements, fixes for test suite, and cherry-picked 4-2-stable changes (main)

- storage_tiering.cpp
This gets the plugin building again
> [#216] storage_tiering.cpp: add missing execMyRule.h include

- packaging/test_plugin_unified_storage_tiering.py
This tweak was taken from #224.
Without this, it's possible for the test to fail due to the access time not appearing to change. The real issue is that the access time doesn't provide enough accuracy to detect fast changes.
> [#206] Make test results consistent (main)

- README.md
- exec_as_user.hpp
- libirods_rule_engine_plugin-unified_storage_tiering.cpp
- packaging/test_plugin_unified_storage_tiering.py
- proxy_connection.hpp
- storage_tiering.cpp
- storage_tiering.hpp
Hi,
This is a first try at adapting using storage tiering for data from remote sites.
The file `"exec_as_user.hpp"` has:
```
rodsLog(
LOG_ERROR,
"executing as user [%s] fom zone [%s]",
user.userName,
user.rodsZone);
```
It shows that the correct user and remote zone is being used after the modifications:
```
{"log_category":"legacy","log_level":"error","log_message":"executing as user [robertv] fom zone [igor]","request_api_name":"EXEC_RULE_EXPRESSION_AN","request_api_number":1206,"request_api_version":"d","request_client_user":"rods","request_host":"145.100.3.238","request_proxy_user":"rods","request_release_version":"rods4.3.1","server_host":"irodstest1.storage.surfsara.nl","server_pid":22550,"server_timestamp":"2023-11-21T10:35:09.037Z","server_type":"agent","server_zone":"frank"}
``` …
> Implement storage tiering for data from remote zones

- packaging/test_plugin_unified_storage_tiering.py
- storage_tiering.cpp
- storage_tiering.hpp
Implement fix for: https://github.com/irods/irods_capability_storage_tiering/issues/233
> implement preserve.replicas when restaging files

- unified_storage_tiering.cmake
In service of irods/irods#6251
Ignore the branch name
> [irods/irods#6251] do not explicitly link to fmt (main)

- unified_storage_tiering.cmake
In service of irods/irods#6251
> [irods/irods#6251] do not explicitly link to fmt (4-3-stable)

- irods_consortium_continuous_integration_test_hook.py
Addresses #275
Tests are still running, but this problem isn't happening anymore, so that's good.
> [#275] Test hook: Remove unnecessary unittest-xml-reporting installation (4-3-stable)

- CMakeLists.txt
- irods_consortium_continuous_integration_build_hook.py
- src/main.cpp
- src/storage_tiering.cpp
Addresses #286
Addresses #287 
Addresses #288 
Need to run test suite, but basic things like tiering out and restaging seem to be working.
> Add ASAN support and fix memleaks (4-3-stable)

- CMakeLists.txt
- irods_consortium_continuous_integration_build_hook.py
- src/main.cpp
- src/storage_tiering.cpp
Addresses #286 
Addresses #287 
Addresses #288
Cherry-pick of #289
Tests are not passing due to #290. However, there isn't much difference between this and 4-3-stable, so maybe it's okay...
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b2d4a79..9197f7d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,6 @@
cmake_minimum_required(VERSION 3.5.0 FATAL_ERROR) #CPACK_DEBIAN_<COMPONENT>_PACKAGE_NAME
-set(IRODS_MINIMUM_VERSION "4.3.3")
+set(IRODS_MINIMUM_VERSION "4.90.0")
find_package(IRODS "${IRODS_MINIMUM_VERSION}" REQUIRED)
set(IRODS_PLUGIN_REVISION "0")
set(IRODS_PLUGIN_VERSION "${IRODS_MINIMUM_VERSION}.${IRODS_PLUGIN_REVISION}")
@@ -22,7 +22,6 @@ project(irods_capability-storage_tiering
include("${IRODS_TARGETS_PATH}")
include(GNUInstallDirs)
-include(UseLibCXX)
if …
```
> Add ASAN support and fix memleaks (main)

- .clang-format
- include/irods/private/storage_tiering/proxy_connection.hpp
- packaging/test_plugin_unified_storage_tiering.py
- src/main.cpp
- src/storage_tiering.cpp
Addresses #164 
Addresses #189 
Addresses #273
Addresses #293 
A few notes with this change:
1. Leaving in draft for now since I need to run the full test suite and make sure things are working when built against true-blue 4.3.3 packages. The build hook currently requires you to provide iRODS packages so I want to make extra sure I haven't been testing against tip of 4-3-stable or something that is not bit-for-bit identical to 4.3.3 iRODS packages.
2. I didn't change any of the internal interfaces (e.g. removing the user and zone parameters from function signatures), but we can update those if desired. Felt like a bit of a clean-up maneuver, distracting from the meat of the change.
3. "Run all storage tiering ops as admin" is not quite accurate as updating access_time metadata is not …
> Fix tiering with complex permissions and rodsusers running tiering rules (4-3-stable)

- .clang-format
- include/irods/private/storage_tiering/proxy_connection.hpp
- packaging/test_plugin_unified_storage_tiering.py
- src/main.cpp
- src/storage_tiering.cpp
Addresses https://github.com/irods/irods_capability_storage_tiering/issues/164
Addresses https://github.com/irods/irods_capability_storage_tiering/issues/189
Addresses https://github.com/irods/irods_capability_storage_tiering/issues/273
Addresses https://github.com/irods/irods_capability_storage_tiering/issues/293
Cherry-picked from #295
> Fix tiering with complex permissions and rodsusers running tiering rules (main)

- README.md
- packaging/test_plugin_unified_storage_tiering.py
- src/data_verification_utilities.cpp
- src/storage_tiering.cpp
Addresses #281 
Cherry-picked from https://github.com/irods/irods_capability_storage_tiering/pull/329
> [#281] Fix tiering out objects with 'select' in name (main)

- packaging/test_plugin_unified_storage_tiering.py
- src/data_verification_utilities.cpp
- src/main.cpp
- src/storage_tiering.cpp
Addresses #283 
In service of #290
Addresses #300 
Almost all the tests passed for postgres, but they failed on mysql. I'm guessing this has to do with https://github.com/irods/irods_capability_storage_tiering/issues/279, which is rooted in irods/irods#8154.
There is one test which did not pass that we can figure out separately as part of resolving #290 (hence, "In service of" rather than "Addresses" above). You can read about / discuss the failure here: https://github.com/irods/irods_capability_storage_tiering/issues/290#issuecomment-2773263784
> Add setup/teardown, fix failing tests (main) 

- include/irods/private/storage_tiering/data_verification_utilities.hpp
- include/irods/private/storage_tiering/storage_tiering.hpp
- src/data_verification_utilities.cpp
- src/main.cpp
- src/storage_tiering.cpp
In service of #290 
This fixes the one known failing test by escaping logical paths before using them with internal GenQueries. 
Also fixed some include ordering issues (and ran clang-format). I kept that in a separate commit to make the salient change easier to see.
Running full test suite now.
> [#290] Escape data object paths for GenQuery (main)
